version: '3'

services:
    redis-server:
       image: 'redis'
    node-app:
       # restart policy
       restart: always 
       build: .
       ports: 
          - "4004:8081"
         #  local:container  